# Generated by Django 3.2.3 on 2021-06-02 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='schemas title')),
                ('sepataror', models.TextField(verbose_name='columns separator')),
                ('character', models.TextField(verbose_name='string character')),
                ('modified', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='schemas owner')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.TextField(verbose_name='column name')),
                ('column_type', models.CharField(choices=[('full_name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('domain_name', 'Domain name'), ('phone_number', 'Phone number'), ('company_name', 'Company name'), ('text', 'Text'), ('integer', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=30, verbose_name='columns type')),
                ('patameters', models.TextField(verbose_name='patametersr')),
                ('order', models.IntegerField(verbose_name='order')),
                ('schema_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakecsv_app.schema', verbose_name='list of schema')),
            ],
        ),
    ]
