# Generated by Django 3.2.3 on 2021-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='patameters',
        ),
        migrations.AddField(
            model_name='list',
            name='parameters',
            field=models.TextField(null=True, verbose_name='parameters'),
        ),
    ]
