# Generated by Django 3.2.3 on 2021-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0002_auto_20210602_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='column_name',
            field=models.TextField(max_length=100, verbose_name='column name'),
        ),
        migrations.AlterField(
            model_name='list',
            name='parameters',
            field=models.TextField(max_length=100, null=True, verbose_name='parameters'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='character',
            field=models.TextField(max_length=100, verbose_name='string character'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='sepataror',
            field=models.TextField(max_length=100, verbose_name='columns separator'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='title',
            field=models.TextField(max_length=100, verbose_name='schemas title'),
        ),
    ]
