# Generated by Django 3.2.3 on 2021-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0004_auto_20210609_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='character',
            field=models.CharField(max_length=30, verbose_name='string character'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='sepataror',
            field=models.CharField(max_length=30, verbose_name='columns separator'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='title',
            field=models.CharField(max_length=30, verbose_name='schemas title'),
        ),
    ]
