# Generated by Django 3.2.3 on 2021-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0005_auto_20210609_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='column_name',
            field=models.CharField(max_length=30, verbose_name='column name'),
        ),
        migrations.AlterField(
            model_name='list',
            name='parameters',
            field=models.CharField(max_length=30, null=True, verbose_name='parameters'),
        ),
    ]
