# Generated by Django 3.2.3 on 2021-06-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0006_auto_20210609_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='schema_id',
        ),
        migrations.AddField(
            model_name='list',
            name='schema_id',
            field=models.ManyToManyField(to='fakecsv_app.Schema', verbose_name='list of schema'),
        ),
    ]
