# Generated by Django 3.2.3 on 2021-06-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0007_auto_20210614_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='schema_id',
        ),
        migrations.AddField(
            model_name='list',
            name='schema_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakecsv_app.schema', verbose_name='list of schema'),
        ),
    ]
