# Generated by Django 3.2.3 on 2021-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0008_auto_20210614_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='link',
            field=models.CharField(default=1, max_length=30, verbose_name='schemas link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='status',
            field=models.CharField(choices=[(0, 'ready to generate'), (1, 'processing'), (2, 'ready to download')], default=1, max_length=30, verbose_name='schemas type'),
            preserve_default=False,
        ),
    ]
