# Generated by Django 3.2.3 on 2021-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0009_auto_20210615_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='status',
            field=models.IntegerField(choices=[(0, 'ready to generate'), (1, 'processing'), (2, 'ready to download')], max_length=30, verbose_name='schemas type'),
        ),
    ]
