# Generated by Django 3.2.3 on 2021-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0010_alter_schema_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='parameters',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='parameters'),
        ),
    ]
