# Generated by Django 3.2.3 on 2021-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0011_alter_list_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='status',
            field=models.CharField(choices=[('ready_to_generate', 'ready to generate'), ('processing', 'processing'), ('ready_to_download', 'ready to download')], max_length=30, verbose_name='schemas type'),
        ),
    ]
