# Generated by Django 3.2.3 on 2021-06-16 10:25

from django.db import migrations, models
import django.db.models.deletion
import fakecsv_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0012_alter_schema_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fakecsv_app.models.file_path)),
                ('schema_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakecsv_app.schema', verbose_name='file of schema')),
            ],
        ),
    ]
