# Generated by Django 3.2.3 on 2021-06-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0014_auto_20210616_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='file_id',
        ),
        migrations.AddField(
            model_name='file',
            name='schema_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakecsv_app.schema', verbose_name='file of schema'),
        ),
    ]
