# Generated by Django 3.2.3 on 2021-06-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv_app', '0015_auto_20210616_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
